### PR TITLE
Sanitize markdown html

### LINKED ISSUE #21: Handle sanitation because markdown
https://hexdocs.pm/earmark/Earmark.html#module-security

### Security

Please be aware that Markdown is not a secure format. It produces HTML from Markdown and HTML. **It is your job to sanitize and or filter the output of Markdown.html** if you cannot trust the input and are to serve the produced HTML on the Web.

### PR DESCRIPTION
**Pull request by marvelm**
Resolves #21 

I've implemented a simple whitelist-based sanitizer for the HTML produced by Earmark. I can add more tags/attributes to the whitelist if needed.

### CODE REVIEW

**Comment by theangryangel** [comment]
Might be worth looking at https://github.com/rrrene/html_sanitize_ex

**Comment by marvelm** [comment]
@theangryangel, nice find. They've already created a Markdown sanitizer and it seems way more thorough than my implementation. I'll try to use the library some time this week.

[HtmlSanitizeEx.Scrubber.MarkdownHTML](https://github.com/rrrene/html_sanitize_ex/blob/4f7cf6a751beb8a64334a4bd0fc9db176d007947/lib/html_sanitize_ex/scrubber/markdown_html.ex)
[HtmlSanitizeEx.markdown_html](https://github.com/rrrene/html_sanitize_ex/blob/a7065c91f95b89b69baf52e4ab34654719620b3f/lib/html_sanitize_ex.ex#L16)

**Comment by knewter** [comment]
Thanks for the contribution! Let me know how the `html_sanitize_ex` work goes and I'm glad to merge whatever you end up on

**Comment by knewter** [comment]
@marvelm any update on this? Thanks tons btw

**Comment by marvelm** [comment]
@knewter I had to upgrade the `mochiweb` dependency in `html_sanitize_ex` in order to avoid a version conflict with `floki`. I have a fork of `html_sanitize_ex` for now, I'll update this branch as soon the maintainer accepts my pull request.

**Comment by knewter** [comment]
That's exciting. Thanks for the update! :)

**Comment by marvelm** [comment]
@knewter This PR is ready for review now.

**Comment by knewter** [comment]
So simple, nothing to say but :+1:. Well, almost nothing - crazy that it removes the \n but whatevs. Thanks!

**Pull request merged**
